### ISSUE TITLE
The text was abnormally cleared when filling in the Comment text field in the reward mode box

### ISSUE THREAD

**Issue by huanli233** [clarkwinkelmann/flarum-ext-money-rewards#1]
**The text was abnormally cleared when filling in the Comment text field in the reward mode box.**

**Comment by clarkwinkelmann** [comment]
I need more details. Do you have a screenshot or video you can share?

You mean the text you are currently writing is being cleared unexpectedly, or a text input is being cleared while typing in a different one?

Please include your `php flarum info` and if you can, try disabling other extensions to see if the issue disappears.

**Comment by clarkwinkelmann** [comment]
Closing issue due to lack of information
