### ISSUE TITLE
使用自己编写的zh.yml后显示异常

### ISSUE THREAD

**Issue by March7online** [clarkwinkelmann/flarum-ext-money-rewards#2]
由于打赏信息翻译成中文后有些地方不符合中文语序，于是自己写了一个zh.yml文件上传到了locale文件夹里，但是出现了显示异常的问题，所有的打赏信息完全消失了
![image](https://github.com/user-attachments/assets/66bde507-e3f6-4ef0-9742-b36374687dd9)
![image](https://github.com/user-attachments/assets/dab5e7d5-e8b0-42fa-bf75-e9b756fd02a7)
最后附上我的zh.yml的txt文件
[zh.yml.txt](https://github.com/user-attachments/files/17145218/zh.yml.txt)

**Comment by March7online** [comment]
又测试了一下，显示并没有问题，但是我的文件也并没有生效

**Comment by March7online** [comment]
解决了，是简体中文的语言包的问题

**Comment by clarkwinkelmann** [comment]
Hello, if you encounter issues in the future it would be easier for me to discuss the problem in English.

This indeed looked like a language pack issue, but if a similar problem happens again, please share your `php flarum info` output and check whether there are any javascript errors in the browser development tab https://docs.flarum.org/troubleshoot

I'm glad to hear the problem has been resolved.
